import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1742866354594 implements MigrationInterface {
    name = 'Migration1742866354594'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_details" ("user_details_id" SERIAL NOT NULL, "personal_email" character varying NOT NULL, "personal_phone" character varying NOT NULL, "residential_country" character varying NOT NULL, "country_nationality" character varying NOT NULL, "emergency_contact_name" character varying NOT NULL, "emergency_contact_phone" character varying NOT NULL, "re_hirable" boolean, "hire_date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_a3b600bcc8958132f9597d78dfb" UNIQUE ("personal_email"), CONSTRAINT "UQ_bac57c1d83283df54f62a5d112c" UNIQUE ("personal_phone"), CONSTRAINT "UQ_5dd2282f7eab1a9283b62f0c5cc" UNIQUE ("emergency_contact_phone"), CONSTRAINT "PK_2def7d986359edfd93a840f7f30" PRIMARY KEY ("user_details_id"))`);
        await queryRunner.query(`CREATE TABLE "documents" ("document_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_name" character varying(255) NOT NULL DEFAULT 'article-document', "file_type" "public"."documents_file_type_enum" NOT NULL DEFAULT 'unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bec3c89789f76e330bbe1766b2c" PRIMARY KEY ("document_id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("tag_id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "PK_06a35221325edeb80ad2ec1ff85" PRIMARY KEY ("tag_id"))`);
        await queryRunner.query(`CREATE TABLE "articles" ("article_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "article_name" character varying NOT NULL, "article_edit_available" boolean NOT NULL DEFAULT true, "article_status" "public"."articles_article_status_enum" NOT NULL DEFAULT 'draft', "user_id" uuid, "user_update_id" uuid, "document_id" uuid, "topic_id" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_cc6a6d8e02153b7e65b3cb2ef2" UNIQUE ("document_id"), CONSTRAINT "PK_b9a16e8d0dc20426e1611e560bc" PRIMARY KEY ("article_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87bb15395540ae06337a486a77" ON "articles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e94bb91d735cbb4d7ab051d68" ON "articles" ("user_update_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc6a6d8e02153b7e65b3cb2ef2" ON "articles" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_339ac5a85fd438b19f3466ddb2" ON "articles" ("topic_id") `);
        await queryRunner.query(`CREATE TABLE "topics" ("topic_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "topic_name" character varying NOT NULL, "topic_edit_available" boolean NOT NULL DEFAULT true, "user_id" uuid, "category_id" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9162cacd23580d0fce1f7c6bbe0" PRIMARY KEY ("topic_id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("category_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_name" character varying NOT NULL, "category_edit_available" boolean NOT NULL DEFAULT true, "user_id" uuid, "client_id" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_51615bef2cea22812d0dcab6e18" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2296b7fe012d95646fa41921c8" ON "categories" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdc35e782536ba73f64443ecc1" ON "categories" ("client_id") `);
        await queryRunner.query(`CREATE TABLE "clients" ("client_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_name" character varying NOT NULL, "client_edit_available" boolean NOT NULL DEFAULT true, "user_id" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_49e91f1e368e3f760789e7764aa" PRIMARY KEY ("client_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_07a7a09b04e7b035c9d90cf498" ON "clients" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("permission_id" SERIAL NOT NULL, "permission_name" character varying NOT NULL, "app_module" character varying NOT NULL, CONSTRAINT "PK_1717db2235a5b169822e7f753b1" PRIMARY KEY ("permission_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("role_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_name" character varying NOT NULL, "role_status" "public"."roles_role_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_09f4c8130b54f35925588a37b6a" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TABLE "assignments" ("assignment_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignment_name" character varying NOT NULL, CONSTRAINT "PK_d6c1d70f2bb5464c5b3a5269bb9" PRIMARY KEY ("assignment_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60f0c98ab2a36e1d6daee24be3" ON "assignments" ("assignment_name") `);
        await queryRunner.query(`CREATE TABLE "announcement_acknowledgements" ("user_id" uuid NOT NULL, "announcement_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a32151fc0a124d9399849b62be3" PRIMARY KEY ("user_id", "announcement_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fff328f0ce8095b32943885d77" ON "announcement_acknowledgements" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92231da7a1aecb4833b5c29fd9" ON "announcement_acknowledgements" ("announcement_id") `);
        await queryRunner.query(`CREATE TABLE "announcements" ("announcement_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "priority_level" "public"."announcements_priority_level_enum" NOT NULL DEFAULT 'low', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "document_id" uuid, CONSTRAINT "REL_d171f2cc4ad0ff34bb7c0b906c" UNIQUE ("document_id"), CONSTRAINT "PK_e6a88fded26412583072e5f745f" PRIMARY KEY ("announcement_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e02da2019c7fcdbbd5d30b681" ON "announcements" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d171f2cc4ad0ff34bb7c0b906c" ON "announcements" ("document_id") `);
        await queryRunner.query(`CREATE TABLE "custom_fields" ("field_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "field_name" character varying NOT NULL, "data_type" "public"."custom_fields_data_type_enum" NOT NULL DEFAULT 'string', "visibility" "public"."custom_fields_visibility_enum" NOT NULL DEFAULT 'private', "status" "public"."custom_fields_status_enum" NOT NULL DEFAULT 'inactive', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0154f23cfd11f6fe4844fb8a664" UNIQUE ("field_name"), CONSTRAINT "PK_09d45312d3d5eb8caeabb18c3e3" PRIMARY KEY ("field_id"))`);
        await queryRunner.query(`CREATE TABLE "user_custom_field_values" ("value_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" character varying, "user_id" uuid NOT NULL, "field_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf65addc007497390177d893ce9" PRIMARY KEY ("value_id", "user_id", "field_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_field" ON "user_custom_field_values" ("user_id", "field_id") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "users" ("user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "work_email" character varying NOT NULL, "work_phone" character varying NOT NULL, "selectable_as_leader" boolean NOT NULL DEFAULT false, "job_title" character varying NOT NULL, "user_details_id" integer NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "user_edit_available" boolean NOT NULL DEFAULT true, "role_id" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bfdc1638ad4f831a90e5300364a" UNIQUE ("work_email"), CONSTRAINT "UQ_48c48ef951e15dbca65f97e468c" UNIQUE ("work_phone"), CONSTRAINT "REL_fcae649d1b01de4a5befc8114e" UNIQUE ("user_details_id"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "user_reports_to" ("reporting_user_id" uuid NOT NULL, "reports_to_user_id" uuid NOT NULL, CONSTRAINT "PK_810494f929c855b9e60845b39fd" PRIMARY KEY ("reporting_user_id", "reports_to_user_id"))`);
        await queryRunner.query(`CREATE TABLE "staff_directory_order" ("order" SERIAL NOT NULL, "column_name" character varying NOT NULL, CONSTRAINT "UQ_5c2d0340c189f06d4424944ba02" UNIQUE ("column_name"), CONSTRAINT "PK_6d23d677d00b6eed00a9a20b554" PRIMARY KEY ("order"))`);
        await queryRunner.query(`CREATE TABLE "tags_articles_articles" ("tagsTagId" integer NOT NULL, "articlesArticleId" uuid NOT NULL, CONSTRAINT "PK_5adbe217eb4cb1de656b895f8bf" PRIMARY KEY ("tagsTagId", "articlesArticleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_027706f9f40b70c38f30d30444" ON "tags_articles_articles" ("tagsTagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d32ef8160c54cad8f79601998f" ON "tags_articles_articles" ("articlesArticleId") `);
        await queryRunner.query(`CREATE TABLE "article_tags" ("article_id" uuid NOT NULL, "tag_id" integer NOT NULL, CONSTRAINT "PK_dd79accc42e2f122f6f3ff7588a" PRIMARY KEY ("article_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f8c9234a4c4cb37806387f0c9e" ON "article_tags" ("article_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1325dd0b98ee0f8f673db6ce19" ON "article_tags" ("tag_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_clients" ("user_id" uuid NOT NULL, "client_id" uuid NOT NULL, CONSTRAINT "PK_4268e8b3cb99496f8c14d9dcfd6" PRIMARY KEY ("user_id", "client_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_912252a5a68db6b9893e4308fe" ON "user_clients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_801aaecb0fe196760e007d80f0" ON "user_clients" ("client_id") `);
        await queryRunner.query(`CREATE TABLE "user_assignments" ("user_id" uuid NOT NULL, "assignment_id" uuid NOT NULL, CONSTRAINT "PK_4debed0f50892c68f495b1f5c42" PRIMARY KEY ("user_id", "assignment_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7f08d4f30bf35eb617d8c7a34" ON "user_assignments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_545fedaff15184b913739c02fd" ON "user_assignments" ("assignment_id") `);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_87bb15395540ae06337a486a77a" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_9e94bb91d735cbb4d7ab051d68d" FOREIGN KEY ("user_update_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_cc6a6d8e02153b7e65b3cb2ef26" FOREIGN KEY ("document_id") REFERENCES "documents"("document_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_339ac5a85fd438b19f3466ddb2f" FOREIGN KEY ("topic_id") REFERENCES "topics"("topic_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "FK_d6c99a7b01054f5178882192940" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "FK_55f03ccaeee22a418c4b00b83a2" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_2296b7fe012d95646fa41921c8b" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_bdc35e782536ba73f64443ecc15" FOREIGN KEY ("client_id") REFERENCES "clients"("client_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_acknowledgements" ADD CONSTRAINT "FK_fff328f0ce8095b32943885d773" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_acknowledgements" ADD CONSTRAINT "FK_92231da7a1aecb4833b5c29fd91" FOREIGN KEY ("announcement_id") REFERENCES "announcements"("announcement_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_2e02da2019c7fcdbbd5d30b6816" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_d171f2cc4ad0ff34bb7c0b906c8" FOREIGN KEY ("document_id") REFERENCES "documents"("document_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_custom_field_values" ADD CONSTRAINT "FK_dcc6d0164bfb56516ee5c2142fe" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_custom_field_values" ADD CONSTRAINT "FK_ad22fa081370f6c7b24794ef92f" FOREIGN KEY ("field_id") REFERENCES "custom_fields"("field_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_fcae649d1b01de4a5befc8114e8" FOREIGN KEY ("user_details_id") REFERENCES "user_details"("user_details_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports_to" ADD CONSTRAINT "FK_1c7b15f8c90177b370ab0938837" FOREIGN KEY ("reporting_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports_to" ADD CONSTRAINT "FK_6f4379e5d2e9f8df9874bdd9bd5" FOREIGN KEY ("reports_to_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags_articles_articles" ADD CONSTRAINT "FK_027706f9f40b70c38f30d304447" FOREIGN KEY ("tagsTagId") REFERENCES "tags"("tag_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tags_articles_articles" ADD CONSTRAINT "FK_d32ef8160c54cad8f79601998fe" FOREIGN KEY ("articlesArticleId") REFERENCES "articles"("article_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_tags" ADD CONSTRAINT "FK_f8c9234a4c4cb37806387f0c9e9" FOREIGN KEY ("article_id") REFERENCES "articles"("article_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "article_tags" ADD CONSTRAINT "FK_1325dd0b98ee0f8f673db6ce194" FOREIGN KEY ("tag_id") REFERENCES "tags"("tag_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_clients" ADD CONSTRAINT "FK_912252a5a68db6b9893e4308fe3" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_clients" ADD CONSTRAINT "FK_801aaecb0fe196760e007d80f06" FOREIGN KEY ("client_id") REFERENCES "clients"("client_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_assignments" ADD CONSTRAINT "FK_d7f08d4f30bf35eb617d8c7a34e" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_assignments" ADD CONSTRAINT "FK_545fedaff15184b913739c02fd1" FOREIGN KEY ("assignment_id") REFERENCES "assignments"("assignment_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_assignments" DROP CONSTRAINT "FK_545fedaff15184b913739c02fd1"`);
        await queryRunner.query(`ALTER TABLE "user_assignments" DROP CONSTRAINT "FK_d7f08d4f30bf35eb617d8c7a34e"`);
        await queryRunner.query(`ALTER TABLE "user_clients" DROP CONSTRAINT "FK_801aaecb0fe196760e007d80f06"`);
        await queryRunner.query(`ALTER TABLE "user_clients" DROP CONSTRAINT "FK_912252a5a68db6b9893e4308fe3"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "article_tags" DROP CONSTRAINT "FK_1325dd0b98ee0f8f673db6ce194"`);
        await queryRunner.query(`ALTER TABLE "article_tags" DROP CONSTRAINT "FK_f8c9234a4c4cb37806387f0c9e9"`);
        await queryRunner.query(`ALTER TABLE "tags_articles_articles" DROP CONSTRAINT "FK_d32ef8160c54cad8f79601998fe"`);
        await queryRunner.query(`ALTER TABLE "tags_articles_articles" DROP CONSTRAINT "FK_027706f9f40b70c38f30d304447"`);
        await queryRunner.query(`ALTER TABLE "user_reports_to" DROP CONSTRAINT "FK_6f4379e5d2e9f8df9874bdd9bd5"`);
        await queryRunner.query(`ALTER TABLE "user_reports_to" DROP CONSTRAINT "FK_1c7b15f8c90177b370ab0938837"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_fcae649d1b01de4a5befc8114e8"`);
        await queryRunner.query(`ALTER TABLE "user_custom_field_values" DROP CONSTRAINT "FK_ad22fa081370f6c7b24794ef92f"`);
        await queryRunner.query(`ALTER TABLE "user_custom_field_values" DROP CONSTRAINT "FK_dcc6d0164bfb56516ee5c2142fe"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_d171f2cc4ad0ff34bb7c0b906c8"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_2e02da2019c7fcdbbd5d30b6816"`);
        await queryRunner.query(`ALTER TABLE "announcement_acknowledgements" DROP CONSTRAINT "FK_92231da7a1aecb4833b5c29fd91"`);
        await queryRunner.query(`ALTER TABLE "announcement_acknowledgements" DROP CONSTRAINT "FK_fff328f0ce8095b32943885d773"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_bdc35e782536ba73f64443ecc15"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_2296b7fe012d95646fa41921c8b"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_55f03ccaeee22a418c4b00b83a2"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_d6c99a7b01054f5178882192940"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_339ac5a85fd438b19f3466ddb2f"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_cc6a6d8e02153b7e65b3cb2ef26"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_9e94bb91d735cbb4d7ab051d68d"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_87bb15395540ae06337a486a77a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_545fedaff15184b913739c02fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7f08d4f30bf35eb617d8c7a34"`);
        await queryRunner.query(`DROP TABLE "user_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_801aaecb0fe196760e007d80f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_912252a5a68db6b9893e4308fe"`);
        await queryRunner.query(`DROP TABLE "user_clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1325dd0b98ee0f8f673db6ce19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8c9234a4c4cb37806387f0c9e"`);
        await queryRunner.query(`DROP TABLE "article_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d32ef8160c54cad8f79601998f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_027706f9f40b70c38f30d30444"`);
        await queryRunner.query(`DROP TABLE "tags_articles_articles"`);
        await queryRunner.query(`DROP TABLE "staff_directory_order"`);
        await queryRunner.query(`DROP TABLE "user_reports_to"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_field"`);
        await queryRunner.query(`DROP TABLE "user_custom_field_values"`);
        await queryRunner.query(`DROP TABLE "custom_fields"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d171f2cc4ad0ff34bb7c0b906c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e02da2019c7fcdbbd5d30b681"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92231da7a1aecb4833b5c29fd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fff328f0ce8095b32943885d77"`);
        await queryRunner.query(`DROP TABLE "announcement_acknowledgements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60f0c98ab2a36e1d6daee24be3"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a7a09b04e7b035c9d90cf498"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdc35e782536ba73f64443ecc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2296b7fe012d95646fa41921c8"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "topics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_339ac5a85fd438b19f3466ddb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc6a6d8e02153b7e65b3cb2ef2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e94bb91d735cbb4d7ab051d68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87bb15395540ae06337a486a77"`);
        await queryRunner.query(`DROP TABLE "articles"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TABLE "user_details"`);
    }

}
